const MOCK = {
    aud:"## Audiências principais (1P iFood)\n\n| Segmento | Descrição | Estimativa | Potencial |\n| --- | --- | --- | --- |\n| **Heavy buyers bebidas** | 3+ pedidos bebidas/90d | ~4,2 MM | Alto ROAS em Meta |\n| **Fim de semana noturno** | Pedidos sex–dom 19h–01h | ~8,1 MM | Volume + remarketing |\n| **Ticket premium** | Ticket médio > P75 categoria | ~1,8 MM | CAC maior, LTV forte |\n| **Lookalike conversores** | Seed últimos 30d | ~12 MM | Expansão controlada |\n\n**Próximo passo:** priorize *Heavy buyers* + *FDS noturno* para escala com ROAS > 4x.",
    plan:"## Plano de mídia — Maio (R$ 250.000)\n\nObjetivo: **pedidos incrementais** com **ROAS > 4x**.\n\n| Plataforma | Budget | % | Foco |\n| --- | --- | --- | --- |\n| **Meta Ads** | R$ 145.000 | 58% | Feed/Stories, criativos UGC + catálogo |\n| **Google Ads** | R$ 80.000 | 32% | Search marca + campanhas de performance |\n| **TikTok Ads** | R$ 25.000 | 10% | Spark + testes de ângulo |\n\n- **Semana 1–2:** 55/35/10 até estabilizar CPA.\n- **Semana 3–4:** realocar +5–10% para a plataforma com melhor *iROAS* na Advolve.\n\n`Nota:` pacing por janela 19h–22h conforme histórico.",
    hyp:"## 4 hipóteses de audiência — bebidas premium (fds noite)\n\n1. **`Premium Night OWL`** — Usuários com pedidos de bebidas premium após 20h sex–dom. Tamanho estimado **~2,1 MM**. ROAS previsto **4,6x**. Confiança **média**.\n2. **`Delivery + Supermercado cross`** — Comprou bebidas no mercado e restaurante no mesmo mês. **~3,4 MM**. ROAS **4,2x**. Confiança **alta**.\n3. **`High frequency social`** — 5+ sessões app/semana + interesse em eventos. **~5,8 MM**. ROAS **3,9x**. Confiança **média** (volume vs. pureza).\n4. **`Weekend treat seekers`** — Categoria doces + bebidas no fds. **~6,2 MM**. ROAS **4,1x**. Confiança **média-alta**.\n\nSugestão: testar em *Meta* com orçamento 70/30 contra *lookalike* atual.",
    ins:"## 5 insights acionáveis\n\n- **Pico 19h–22h:** concentre *~40%* do spend nessa janela; histórico mostra **2,3x** mais pedidos.\n- **Criativo líder:** *Frete grátis* responde por **34%** das conversões — planejar variações IA para fadiga.\n- **Audiência A:** **+42%** vs benchmark; escalar **+30%** budget com teto de frequência.\n- **Novos compradores:** **39%** dos pedidos vs **28%** média ecossistema — manter recência como sinal no modelo.\n- **TikTok:** ROAS estável mas volume baixo; testar **2 novos hooks** antes de aumentar share.\n\nQuer que eu detalhe *regras de exclusão* ou *mapa de criativos*?",
    default:"## Resposta (demo)\n\nNão foi possível usar o Claude agora (API indisponível ou sem chave no servidor). Esta é uma **resposta simulada**.\n\nPara respostas reais: na pasta do projeto rode `npm start`, defina `ANTHROPIC_API_KEY` e abra **http://localhost:3780**.\n\nEnquanto isso, experimente os atalhos **Consultar audiências**, **Plano de mídia**, **Novas audiências** ou **Insights**."
  }

var PROJECT_DATA=[
    /* 0: Bebidas Premium · Coca-Cola — ativo */
    {period:"Relatório Final · Abril 2026 (01/04 a 30/04)",opPeriod:"Período: 01/04 a 23/04 · Relatório Parcial",
     heroOrders:"+2.340 pedidos",hfIncrVal:"+2.340",hfRoasVal:"4.7x",hfRoasDelta:"+12.1% mês anterior",hfCacVal:"−27%",hfCacDelta:"R$ 14,20 atual",
     bnImpVal:"12.4M",bnImpDelta:"+18.2% vs. mês anterior",bnOrdVal:"8.241",bnOrdDelta:"+31.4% vs. mês anterior",
     bnRoasVal:"4.7x",bnRoasSub:"Cada R$1 investido retornou R$4,70 em vendas.",bnRoasDelta:"+12.1% vs. mês anterior",
     cacPct:"27%",cacBefore:"R$ 19,50",cacAfter:"R$ 14,20",cacBarPct:73,cacSavings:"R$ 43.600",
     budgetWaste:"40%",budgetDonutPct:60,budgetBefore:"36%",budgetAmount:"R$ 100.000",
     platforms:[{n:"Meta Ads",p:58,c:"#8B5CF6",t:""},{n:"Google Ads",p:32,c:"#C4B5FD",t:"#1a1025"},{n:"TikTok Ads",p:10,c:"#A3E635",t:"#0d0d14"}],
     creatives:[{n:"Promo Frete Grátis",t:"Meta · Feed · Imagem",ctr:"3.4%",roas:"5.2x",conv:"2.841"},{n:"Combo Família",t:"Meta · Stories · Vídeo",ctr:"2.9%",roas:"4.8x",conv:"1.956"},{n:"Desconto 30%",t:"Google · Search · Texto",ctr:"4.1%",roas:"6.1x",conv:"1.623"}],
     insights:[{c:"gr",t:"Audiência A superou benchmark em 42%",d:"Mulheres 25–34 com ticket alto e pedidos noturnos: ROAS 5.2x. Recomendação: aumentar budget em 30%."},
               {c:"pu",t:'Criativo "Frete Grátis" concentra 34% das conversões',d:"Performance estável em Feed e Stories. Derivar 3 variações com IA para testar fadiga criativa."},
               {c:"am",t:"Horário de pico: 19h–22h gera 2.3x mais pedidos",d:"Concentrar 40% do budget nessa janela pode reduzir CAC em ~15%. O agente já ajusta pacing."},
               {c:"bl",t:"Novos compradores: 39% dos pedidos",d:"Acima da média do ecossistema (28%). Segmentação por recência performa acima do esperado."}],
     scaleMult:"13x",scaleTotal:"156",scaleBase:"12",
     opRoas:"1,1",opGmv:"106.502",opPedidos:"2.935",opTicket:"36,28",
     opImp:"11.287.157",opCtr:"4,87%",opCpc:"R$ 0,18",opInvest:"R$ 99.563",
     opDonutPct:27,
     opAuds:[{n:"Modelo\nKMEANS",gmv:"R$82.680",tm:"R$ 37,87",h:105},{n:"Compradores\nCategoria",gmv:"R$22.833",tm:"R$ 31,67",h:71},{n:"Compradores\nInativos",gmv:"R$989",tm:"R$ 31,92",h:19}],
     opAudNote:"A audiência criada via modelo KMEANS é a mais eficaz na relação GMV e ticket médio."},

    /* 1: Delivery Express · Ambev — pausado */
    {period:"Relatório Parcial · Março 2026 (01/03 a 15/03)",opPeriod:"Período: 01/03 a 15/03 · Relatório Parcial",
     heroOrders:"+1.180 pedidos",hfIncrVal:"+1.180",hfRoasVal:"3.2x",hfRoasDelta:"+5.4% mês anterior",hfCacVal:"−14%",hfCacDelta:"R$ 19,60 atual",
     bnImpVal:"8.7M",bnImpDelta:"+9.1% vs. mês anterior",bnOrdVal:"5.104",bnOrdDelta:"+17.8% vs. mês anterior",
     bnRoasVal:"3.2x",bnRoasSub:"Cada R$1 investido retornou R$3,20 em vendas.",bnRoasDelta:"+5.4% vs. mês anterior",
     cacPct:"14%",cacBefore:"R$ 22,80",cacAfter:"R$ 19,60",cacBarPct:86,cacSavings:"R$ 21.400",
     budgetWaste:"28%",budgetDonutPct:48,budgetBefore:"28%",budgetAmount:"R$ 62.000",
     platforms:[{n:"Meta Ads",p:50,c:"#8B5CF6",t:""},{n:"Google Ads",p:40,c:"#C4B5FD",t:"#1a1025"},{n:"TikTok Ads",p:10,c:"#A3E635",t:"#0d0d14"}],
     creatives:[{n:"Entrega Rápida",t:"Meta · Feed · Vídeo",ctr:"2.8%",roas:"3.9x",conv:"1.420"},{n:"Combo Weekend",t:"Meta · Stories · Imagem",ctr:"2.2%",roas:"3.1x",conv:"980"},{n:"Promo Sábado",t:"Google · Display · Banner",ctr:"3.5%",roas:"4.2x",conv:"860"}],
     insights:[{c:"gr",t:"Segmento 25–44 performou 31% acima do esperado",d:"Usuários com padrão de entrega noturna em dias úteis: ROAS 4.1x. Aumentar budget em 25%."},
               {c:"pu",t:'"Entrega Rápida" representa 42% das conversões',d:"Criativo com ângulo de velocidade performa melhor. Derivar variações com novos hooks."},
               {c:"am",t:"Campanha pausada: budget alocado para revisão criativa",d:"Otimização preventiva detectou queda de CTR. Recomendado reativar com novo batch criativo."},
               {c:"bl",t:"Retenção: 19% de recompra no período",d:"Abaixo da meta de 25%. Ativar segmento de reativação com cupom de fidelidade."}],
     scaleMult:"8x",scaleTotal:"96",scaleBase:"12",
     opRoas:"0,8",opGmv:"58.340",opPedidos:"1.624",opTicket:"35,92",
     opImp:"7.420.000",opCtr:"3,21%",opCpc:"R$ 0,24",opInvest:"R$ 72.400",
     opDonutPct:19,
     opAuds:[{n:"Modelo\nKMEANS",gmv:"R$38.200",tm:"R$ 32,10",h:105},{n:"Compradores\nCategoria",gmv:"R$14.800",tm:"R$ 28,50",h:61},{n:"Compradores\nInativos",gmv:"R$5.340",tm:"R$ 29,00",h:35}],
     opAudNote:"O segmento KMEANS mantém maior GMV mesmo com campanha parcialmente pausada."},

    /* 2: Awareness Q2 · Red Bull — finalizado */
    {period:"Relatório Final · Q1 2026 (01/01 a 31/03)",opPeriod:"Período: 01/01 a 31/03 · Relatório Final",
     heroOrders:"+3.890 pedidos",hfIncrVal:"+3.890",hfRoasVal:"5.8x",hfRoasDelta:"+22.4% vs. trimestre anterior",hfCacVal:"−33%",hfCacDelta:"R$ 12,30 atual",
     bnImpVal:"21.3M",bnImpDelta:"+38.4% vs. trimestre anterior",bnOrdVal:"12.780",bnOrdDelta:"+48.2% vs. trimestre anterior",
     bnRoasVal:"5.8x",bnRoasSub:"Cada R$1 investido retornou R$5,80 em vendas.",bnRoasDelta:"+22.4% vs. trimestre anterior",
     cacPct:"33%",cacBefore:"R$ 18,40",cacAfter:"R$ 12,30",cacBarPct:67,cacSavings:"R$ 78.100",
     budgetWaste:"52%",budgetDonutPct:71,budgetBefore:"29%",budgetAmount:"R$ 184.000",
     platforms:[{n:"Meta Ads",p:45,c:"#8B5CF6",t:""},{n:"Google Ads",p:30,c:"#C4B5FD",t:"#1a1025"},{n:"TikTok Ads",p:25,c:"#A3E635",t:"#0d0d14"}],
     creatives:[{n:"Energy Party",t:"TikTok · Feed · Vídeo",ctr:"4.8%",roas:"6.8x",conv:"4.210"},{n:"Sport Challenge",t:"Meta · Reels · Vídeo",ctr:"3.9%",roas:"5.2x",conv:"3.150"},{n:"Summer Vibes",t:"Google · Performance · Adaptável",ctr:"5.1%",roas:"7.1x",conv:"2.890"}],
     insights:[{c:"gr",t:"Audiência 18–24 superou benchmark em 67%",d:"Jovens com padrão de consumo em eventos e bares: ROAS 7.1x. Campanha encerrada no pico."},
               {c:"pu",t:'"Energy Party" gerou 48% das conversões totais',d:"Vídeo vertical no TikTok foi o formato líder. Replicar aprendizado na próxima campanha."},
               {c:"am",t:"TikTok respondeu por 25% do budget e 41% do ROAS",d:"Canal subestimado no plano original. Recomendar aumento de share para próximo ciclo."},
               {c:"bl",t:"Campanha encerrada com meta 34% acima do previsto",d:"Todos os KPIs superaram o benchmark. Relatório final disponível para download."}],
     scaleMult:"18x",scaleTotal:"216",scaleBase:"12",
     opRoas:"2,1",opGmv:"198.750",opPedidos:"5.420",opTicket:"36,67",
     opImp:"18.320.000",opCtr:"6,12%",opCpc:"R$ 0,14",opInvest:"R$ 145.200",
     opDonutPct:34,
     opAuds:[{n:"Modelo\nKMEANS",gmv:"R$142.300",tm:"R$ 39,20",h:105},{n:"Compradores\nCategoria",gmv:"R$41.800",tm:"R$ 33,40",h:74},{n:"Compradores\nInativos",gmv:"R$14.650",tm:"R$ 34,10",h:45}],
     opAudNote:"KMEANS gerou 71% do GMV total — validando a estratégia de segmentação comportamental."},

    /* 3: Remarketing · Heineken — ativo */
    {period:"Relatório Final · Abril 2026 (01/04 a 30/04)",opPeriod:"Período: 01/04 a 23/04 · Relatório Parcial",
     heroOrders:"+1.640 pedidos",hfIncrVal:"+1.640",hfRoasVal:"4.1x",hfRoasDelta:"+8.7% mês anterior",hfCacVal:"−21%",hfCacDelta:"R$ 19,00 atual",
     bnImpVal:"9.8M",bnImpDelta:"+14.3% vs. mês anterior",bnOrdVal:"6.430",bnOrdDelta:"+23.6% vs. mês anterior",
     bnRoasVal:"4.1x",bnRoasSub:"Cada R$1 investido retornou R$4,10 em vendas.",bnRoasDelta:"+8.7% vs. mês anterior",
     cacPct:"21%",cacBefore:"R$ 24,10",cacAfter:"R$ 19,00",cacBarPct:79,cacSavings:"R$ 33.200",
     budgetWaste:"35%",budgetDonutPct:55,budgetBefore:"30%",budgetAmount:"R$ 87.500",
     platforms:[{n:"Meta Ads",p:65,c:"#8B5CF6",t:""},{n:"Google Ads",p:25,c:"#C4B5FD",t:"#1a1025"},{n:"TikTok Ads",p:10,c:"#A3E635",t:"#0d0d14"}],
     creatives:[{n:"Heineken 0.0",t:"Meta · Feed · Imagem",ctr:"3.1%",roas:"4.5x",conv:"2.080"},{n:"Promo Bar",t:"Meta · Stories · Vídeo",ctr:"2.6%",roas:"3.8x",conv:"1.590"},{n:"Festival Season",t:"TikTok · Feed · Vídeo",ctr:"3.8%",roas:"5.0x",conv:"1.320"}],
     insights:[{c:"gr",t:"Segmento masculino 28–40 com ROAS 5.0x em eventos",d:"Usuários com histórico em bares e festas: conversão 2.8x maior. Aumentar alcance em 35%."},
               {c:"pu",t:'"Festival Season" lidera com 32% das conversões',d:"Conteúdo UGC performou melhor que estúdio. Priorizar para próximo ciclo criativo."},
               {c:"am",t:"Janela sex–dom 20h–01h concentra 58% dos pedidos",d:"Pacing noturno de final de semana reduz CPM em 22%. Agente já otimizando."},
               {c:"bl",t:"Taxa de reativação: 31% de compradores inativos convertidos",d:"Segmento lookalike de quem comprou há 60–90 dias: CAC 40% menor que novos."}],
     scaleMult:"11x",scaleTotal:"132",scaleBase:"12",
     opRoas:"1,4",opGmv:"83.620",opPedidos:"2.240",opTicket:"37,33",
     opImp:"8.940.000",opCtr:"4,02%",opCpc:"R$ 0,21",opInvest:"R$ 84.200",
     opDonutPct:31,
     opAuds:[{n:"Modelo\nKMEANS",gmv:"R$58.400",tm:"R$ 38,90",h:105},{n:"Compradores\nCategoria",gmv:"R$19.200",tm:"R$ 30,20",h:64},{n:"Compradores\nInativos",gmv:"R$6.020",tm:"R$ 31,80",h:38}],
     opAudNote:"Remarketing via KMEANS gerou 70% do GMV — estratégia de reativação validada."},

    /* 4: Performance · Smirnoff Ice — finalizado */
    {period:"Relatório Final · Fevereiro 2026 (01/02 a 28/02)",opPeriod:"Período: 01/02 a 28/02 · Relatório Final",
     heroOrders:"+890 pedidos",hfIncrVal:"+890",hfRoasVal:"3.6x",hfRoasDelta:"+7.2% vs. mês anterior",hfCacVal:"−18%",hfCacDelta:"R$ 23,20 atual",
     bnImpVal:"5.2M",bnImpDelta:"+11.4% vs. mês anterior",bnOrdVal:"3.870",bnOrdDelta:"+19.2% vs. mês anterior",
     bnRoasVal:"3.6x",bnRoasSub:"Cada R$1 investido retornou R$3,60 em vendas.",bnRoasDelta:"+7.2% vs. mês anterior",
     cacPct:"18%",cacBefore:"R$ 28,30",cacAfter:"R$ 23,20",cacBarPct:82,cacSavings:"R$ 14.800",
     budgetWaste:"24%",budgetDonutPct:44,budgetBefore:"26%",budgetAmount:"R$ 38.400",
     platforms:[{n:"Meta Ads",p:40,c:"#8B5CF6",t:""},{n:"Google Ads",p:50,c:"#C4B5FD",t:"#1a1025"},{n:"TikTok Ads",p:10,c:"#A3E635",t:"#0d0d14"}],
     creatives:[{n:"Ice Party",t:"Meta · Reels · Vídeo",ctr:"2.4%",roas:"3.8x",conv:"1.240"},{n:"Summer Cool",t:"Google · Performance · Adaptável",ctr:"2.1%",roas:"3.2x",conv:"980"},{n:"Weekend Vibe",t:"TikTok · Feed · Vídeo",ctr:"3.2%",roas:"4.4x",conv:"780"}],
     insights:[{c:"gr",t:"Audiência 21–30 superou projeção em 28%",d:"Público jovem em áreas de entretenimento: ROAS 4.4x via TikTok. Campanha encerrada."},
               {c:"pu",t:'"Weekend Vibe" liderou com ROAS 4.4x via TikTok',d:"Formato vertical com música em alta performou melhor. Replicar na próxima campanha."},
               {c:"am",t:"Google gerou 50% do volume com menor CPM da campanha",d:"Google beneficiou de base 1P robusta. Recomendado manter share elevado."},
               {c:"bl",t:"Campanha encerrada — ROAS 3.6x ficou abaixo da meta de 4x",d:"Revisão de segmentação e criativos recomendada para o próximo ciclo."}],
     scaleMult:"7x",scaleTotal:"84",scaleBase:"12",
     opRoas:"0,9",opGmv:"42.180",opPedidos:"1.180",opTicket:"35,75",
     opImp:"4.820.000",opCtr:"2,84%",opCpc:"R$ 0,29",opInvest:"R$ 48.600",
     opDonutPct:22,
     opAuds:[{n:"Modelo\nKMEANS",gmv:"R$28.400",tm:"R$ 33,20",h:105},{n:"Compradores\nCategoria",gmv:"R$10.800",tm:"R$ 27,80",h:57},{n:"Compradores\nInativos",gmv:"R$2.980",tm:"R$ 28,50",h:28}],
     opAudNote:"Canais em conjunto capturaram 93% do GMV — integração de canais validada."}
  ]

var DRAFTS=[
    {id:"d1",
     name:"iFood Bebidas — Campanha Inverno 2026",
     desc:"Campanha de awareness para bebidas quentes e comfort drinks na plataforma iFood durante os meses de inverno.",
     date:"08/05/2026",stage:"s-done",stageLabel:"Hipóteses aceitas",progress:85,
     missing:["Plano de mídia"],
     brands:["Nestlé","Pilão"],
     objetivo:"Aumentar vendas",kpi:"ROAS",kpiTarget:"4,5x",
     verticais:["B&C (Bebidas e Comida)"],periodo:"45 dias",
     briefing:"Queremos ativar uma campanha de inverno focada em bebidas quentes — chocolate quente, café, chás — aproveitando o comportamento de pedidos em dias frios. O objetivo é crescer penetração de marca em 15% no período de junho a agosto.",
     budget:"R$ 180.000",budgetNum:180000,fee:"R$ 18.000",taxas:"R$ 21.870",midia_valor:"R$ 140.130",
     produtos:"Chocolate Quente Nestlé, Café Pilão, Leão Fuze Tea Quente",
     eans:"7891000100103, 7896005600011",
     midia:null,
     hyps:[
       {title:"Hipótese 1 — Compradores de café em dias frios",status:"accepted",
        pills:[{t:"ROAS prev. 4,8x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~1,2MM usuários",c:""}]},
       {title:"Hipótese 2 — Reativação de heavy buyers inativos",status:"accepted",
        pills:[{t:"ROAS prev. 5,2x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~680k usuários",c:""}]},
       {title:"Hipótese 3 — Lookalike de convertedores Premium",status:"rejected",
        pills:[{t:"ROAS prev. 3,1x",c:""},{t:"Confiança Média",c:""},{t:"~4,8MM usuários",c:""}]}],
     agentCtx:"O período de inverno eleva em <strong>2,3x</strong> a demanda por bebidas quentes na plataforma — janela sazonal com CPM historicamente 18% menor em categorias de comfort food. Os próximos 45 dias apresentam alta favorável para captura incremental de volume com custo de aquisição controlado.",
     agentTrend:"<strong>TikTok</strong> registrou crescimento de 38% em conteúdo relacionado a bebidas quentes nas últimas 4 semanas. Formatos de receita rápida (café, chocolate quente) geram 2,6x mais compartilhamentos que posts de produto isolado. Hashtags com maior tração: <em>#cafédamanhã</em>, <em>#comfortfood</em>, <em>#inverno2026</em>.",
     agentPrice:"Ticket médio projetado da categoria: <strong>R$ 34,80</strong>. Campanhas com bundle (leve 2, pague 1) elevam ticket em 19% historicamente. Preço de entrada sugerido para first-order: <strong>R$ 27,90</strong>. Elasticidade-preço estimada: <strong>−0,7</strong>."},
    {id:"d2",
     name:"Heineken 0.0 — Verão sem Álcool",
     desc:"Introdução da linha Heineken 0.0 para audiências que buscam alternativas sem álcool no iFood.",
     date:"05/05/2026",stage:"s-wait",stageLabel:"Aguardando hipóteses",progress:45,
     missing:["Hipóteses de audiência","Plano de mídia"],
     brands:["Heineken"],
     objetivo:"Novos compradores",kpi:"CPA de primeiro pedido",kpiTarget:"R$ 15,00",
     verticais:["B&C (Bebidas e Comida)"],periodo:"30 dias",
     briefing:"Lançamento da Heineken 0.0 no iFood. Queremos atingir usuários que já compram cervejas regularmente mas podem ter interesse em alternativas sem álcool — especialmente para ocasiões sociais diurnas.",
     budget:"R$ 120.000",budgetNum:120000,fee:"R$ 13.200",taxas:"R$ 14.580",midia_valor:"R$ 92.220",
     produtos:"Heineken 0.0 330ml, Heineken 0.0 pack com 6",
     eans:null,midia:null,hyps:[],
     agentCtx:"Lançamentos no iFood enfrentam um <strong>desafio duplo</strong>: visibilidade em um catálogo extenso e conversão de usuários sem referência prévia. Heineken 0.0 tem abertura em perfis que já consomem cervejas premium mas buscam alternativas para ocasiões diurnas — segmento com baixa competição ativa atualmente.",
     agentTrend:null,agentPrice:null},
    {id:"d3",
     name:"Red Bull — Audiência Gaming",
     desc:"Ativação de audiências jovens com perfil gamer durante eventos e campeonatos de e-sports nacionais.",
     date:"02/05/2026",stage:"s-inc",stageLabel:"Dados incompletos",progress:30,
     missing:["Budget do projeto","EANs dos produtos","Hipóteses de audiência"],
     brands:["Red Bull"],
     objetivo:"Novos compradores",kpi:null,kpiTarget:null,
     verticais:["B&C (Bebidas e Comida)"],periodo:null,
     briefing:"Campanha direcionada ao público gamer, usuários entre 18–28 anos que consomem bebidas energéticas durante sessões de gaming e eventos de e-sports. Queremos associar a marca ao momento de alta performance.",
     budget:null,budgetNum:0,fee:null,taxas:null,midia_valor:null,
     produtos:"Red Bull Energy Drink 250ml, Red Bull Sugar Free",
     eans:null,
     midia:{canais:["Meta","TikTok"],geo:null},
     hyps:[],agentCtx:null,agentTrend:null,agentPrice:null},
    {id:"d4",
     name:"Coca-Cola — Reativação Premium",
     desc:"Campanha de reativação focada em compradores de alto ticket inativos nos últimos 60 dias.",
     date:"29/04/2026",stage:"s-brief",stageLabel:"Briefing inserido",progress:20,
     missing:["Objetivo e meta","Configuração do projeto","Hipóteses de audiência","Plano de mídia"],
     brands:["Coca-Cola"],
     objetivo:null,kpi:null,kpiTarget:null,
     verticais:null,periodo:null,
     briefing:"Precisamos reativar compradores premium da Coca-Cola inativos há 60+ dias. Esses usuários têm ticket médio acima de R$50 e historicamente respondem bem a campanhas de retenção com ofertas exclusivas.",
     budget:null,budgetNum:0,fee:null,taxas:null,midia_valor:null,
     produtos:null,eans:null,midia:null,
     hyps:[],agentCtx:null,agentTrend:null,agentPrice:null},
    {id:"d5",
     name:"Ambev Skol — Fim de Semana",
     desc:"Campanha de performance para Skol com foco em conversão no horário noturno de sexta a sábado.",
     date:"25/04/2026",stage:"s-gen",stageLabel:"Hipóteses geradas",progress:70,
     missing:["Revisão de hipóteses","Plano de mídia"],
     brands:["Ambev — Skol"],
     objetivo:"Aumentar vendas",kpi:"Volume de pedidos",kpiTarget:"8.000 pedidos/mês",
     verticais:["B&C (Bebidas e Comida)"],periodo:"30 dias",
     briefing:"Skol quer capturar o momento de maior consumo: sexta e sábado à noite. Queremos converter usuários que já compraram cerveja nesse horário e expandir para lookalikes de alto potencial.",
     budget:"R$ 95.000",budgetNum:95000,fee:"R$ 10.450",taxas:"R$ 11.543",midia_valor:"R$ 73.008",
     produtos:"Skol Pilsen 350ml, Skol Beats Spirit",
     eans:"7891991010009, 7891991060004",
     midia:{canais:["Meta","Google"],geo:"São Paulo, Rio de Janeiro"},
     hyps:[
       {title:"Hipótese 1 — Heavy buyers noturnos sexta-sábado",status:"pending",
        pills:[{t:"ROAS prev. 5,8x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~3,2MM usuários",c:""}]},
       {title:"Hipótese 2 — Reativação Skol 30–60 dias",status:"pending",
        pills:[{t:"ROAS prev. 4,1x",c:"gr"},{t:"Confiança Média-Alta",c:""},{t:"~1,8MM usuários",c:""}]},
       {title:"Hipótese 3 — Lookalike de convertedores recentes",status:"pending",
        pills:[{t:"ROAS prev. 3,9x",c:"gr"},{t:"Confiança Média-Alta",c:""},{t:"~8,5MM usuários",c:""}]}],
     agentCtx:"Campanhas concentradas no horário de pico (sex–sáb 19h–22h) reduzem CAC em até <strong>22%</strong> e aumentam conversão em <strong>2,1x</strong> vs. horário padrão. O segmento heavy buyer nessa janela representa 3,2MM usuários com propensão de compra acima da média da categoria.",
     agentTrend:"Conteúdo de <strong>sexta à noite</strong> no TikTok cresceu 51% em volume nas últimas 6 semanas. Criativos em formato Spark Ads com cenas de reunião social geram 1,9x mais CTR. Hashtags com maior tração: <em>#findesemana</em>, <em>#cervejageladinha</em>, <em>#sexta</em>.",
     agentPrice:"Ticket médio projetado: <strong>R$ 36,20</strong>. Promoção de pack (6 unidades) eleva ticket em 26% historicamente nesse segmento. Preço de entrada sugerido: <strong>R$ 24,90</strong>. Faixa P75 da categoria: R$ 52,00."}
  ]

var BRANDS=[
    {id:"bnr1",name:"Coca-Cola",initials:"CC",color:"#E8000B",
     cat:"Bebidas · Refrigerante",verticals:["B&C (Bebidas e Comida)"],
     hasLogo:true,hasBrandbook:true,hasFonts:true,inferred:true,inferDate:"08/05/2026",
     fonts:["LMAO Sans","Bebas Neue"],palette:["#F40009","#E8000B","#FFFFFF","#111111","#F5E6C8"]},
    {id:"bnr2",name:"Heineken",initials:"HK",color:"#00843D",
     cat:"Bebidas · Cerveja",verticals:["B&C (Bebidas e Comida)"],
     hasLogo:true,hasBrandbook:true,hasFonts:false,inferred:false,inferDate:"",
     fonts:[],palette:[]},
    {id:"bnr3",name:"Red Bull",initials:"RB",color:"#CC1E4A",
     cat:"Bebidas · Energético",verticals:["B&C (Bebidas e Comida)"],
     hasLogo:true,hasBrandbook:false,hasFonts:false,inferred:false,inferDate:"",
     fonts:[],palette:[]},
    {id:"bnr4",name:"Ambev — Skol",initials:"SK",color:"#F5A623",
     cat:"Bebidas · Cerveja",verticals:["B&C (Bebidas e Comida)"],
     hasLogo:false,hasBrandbook:false,hasFonts:false,inferred:false,inferDate:"",
     fonts:[],palette:[]},
    {id:"bnr5",name:"Smirnoff Ice",initials:"SI",color:"#0052A5",
     cat:"Bebidas · Destilados",verticals:["B&C (Bebidas e Comida)"],
     hasLogo:true,hasBrandbook:true,hasFonts:true,inferred:true,inferDate:"02/05/2026",
     fonts:["GT Walsheim","Helvetica Neue"],palette:["#0052A5","#003880","#FFFFFF","#000000"]}
  ]

var ACCOUNTS=[
    {plat:'google',type:'ifood',id:'123-456-7890',brands:[],projects:[],status:'ok'},
    {plat:'google',type:'new',id:'234-567-8901',brands:['Coca-Cola','Heineken'],projects:['Q1 2025'],status:'partial'},
    {plat:'google',type:'existing',id:'345-678-9012',brands:['Ambev Skol'],projects:[],status:'pending'},
    {plat:'meta',type:'ifood',id:'act_1000000001',brands:[],projects:[],status:'ok'},
    {plat:'meta',type:'new',id:'act_9876543210',brands:['Nike Brasil'],projects:['Brand Launch'],status:'ok'},
    {plat:'tiktok',type:'existing',id:'adv_1234567890',brands:['Samsung'],projects:['Campanha Verão'],status:'pending'}
  ]

var BU_BRANDS={
    "iFood Bebidas":["Coca-Cola","Ambev — Skol","Heineken","Red Bull","Smirnoff Ice"],
    "iFood Mercados":["Pão de Açúcar","Carrefour","Extra"],
    "Pepsico":["Pepsi","Gatorade","H2OH!","Lipton Ice Tea","Lay's","Doritos","Ruffles","Cheetos","Fandangos","Guaraná H2O"],
    "Publicis":["Nivea","Eucerin","La Prairie","Labello","Heineken","Amstel","Eisenbahn","Sol"]
  }

var PROVIDER_ACCOUNTS={
    "Coca-Cola":{
      meta:[{name:"Coca-Cola BR — Feed & Stories",id:"ACC-4821"},{name:"Coca-Cola BR — Retargeting",id:"ACC-4822"}],
      google:[{name:"Coca-Cola BR — Search & Performance",id:"ACC-7734"},{name:"Coca-Cola BR — Display",id:"ACC-7735"}],
      tiktok:[{name:"Coca-Cola BR — TikTok",id:"ACC-8811"}]},
    "Heineken":{
      meta:[{name:"Heineken BR — Brand Awareness",id:"ACC-2211"},{name:"Heineken BR — Conversão",id:"ACC-2212"}],
      google:[{name:"Heineken BR — Search",id:"ACC-5501"}],
      tiktok:[{name:"Heineken BR — TikTok Awareness",id:"ACC-8801"}]},
    "Ambev — Skol":{
      meta:[{name:"Ambev Skol — Feed",id:"ACC-9876"},{name:"Ambev Skol — Stories",id:"ACC-9877"}],
      google:[{name:"Ambev Skol — Performance",id:"ACC-3412"},{name:"Ambev Skol — Search",id:"ACC-3413"}],
      tiktok:[{name:"Ambev Skol — TikTok",id:"ACC-8802"}]},
    "Nestlé":{
      meta:[{name:"Nestlé BR — Feed & Stories",id:"ACC-1101"},{name:"Nestlé BR — Retargeting",id:"ACC-1102"}],
      google:[{name:"Nestlé BR — Search",id:"ACC-4401"},{name:"Nestlé BR — Performance",id:"ACC-4402"}],
      tiktok:[{name:"Nestlé BR — Brand TikTok",id:"ACC-7701"}]},
    "Nescafé":{
      meta:[{name:"Nescafé — Feed Brasil",id:"ACC-1103"}],
      google:[{name:"Nescafé — Search Brasil",id:"ACC-4403"}],
      tiktok:[{name:"Nescafé — TikTok Brasil",id:"ACC-7702"}]},
    "Red Bull":{
      meta:[{name:"Red Bull BR — Awareness",id:"ACC-3301"},{name:"Red Bull BR — Conversão",id:"ACC-3302"}],
      google:[{name:"Red Bull BR — Search",id:"ACC-6601"}],
      tiktok:[{name:"Red Bull BR — TikTok",id:"ACC-9901"},{name:"Red Bull BR — TikTok Festival",id:"ACC-9902"}]},
    "Smirnoff Ice":{
      meta:[{name:"Smirnoff Ice — Feed",id:"ACC-3303"}],
      google:[{name:"Smirnoff Ice — Search",id:"ACC-6602"}],
      tiktok:[{name:"Smirnoff Ice — TikTok",id:"ACC-9903"}]}
  }

var PN_HYPS=[
    {sug:true,
     title:"Hipótese 1 — Compradores frequentes da categoria sem fidelização à marca",
     thesis:"Se ativarmos usuários que compraram na categoria 3 ou mais vezes nas últimas 4 semanas sem nunca converter para a marca, aumentamos penetração aproveitando alta propensão já demonstrada na categoria.",
     rationale:"2,1MM usuários do iFood compraram nessa categoria 3x+ nas últimas 4 semanas sem nenhuma conversão da marca. Ticket médio da categoria: R$38,40. Taxa de conversão esperada: 8,2%. Custo de aquisição estimado: R$9,10.",
     pills:[{t:"ROAS previsto 4,8x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~2,1MM usuários",c:""},{t:"Meta + Google",c:"pu"}],
     pred:{imp:"18,4MM",reach:"6,2MM",clicks:"184K",ctr:"1,00%",cpm:"R$12,40",cpc:"R$1,24",roas:"4,8x"},
     trend:"A categoria registrou pico de buscas orgânicas nas últimas 6 semanas, com crescimento de 34% no TikTok e Instagram Reels. Conteúdo UGC domina o feed; anúncios com formato nativo tendem a 2,1x mais engajamento.",
     price:"Ticket médio projetado: R$38,40 · Faixa P50–P75 da categoria. Campanhas com desconto progressivo em bundles (leve 3 pague 2) elevam ticket em 22% historicamente. Preço de entrada sugerido: R$29,90."},
    {sug:true,
     title:"Hipótese 2 — Reativação de compradores premium inativos (30–90 dias)",
     thesis:"Se reativarmos compradores com ticket acima de R$50 inativos há 30–90 dias, recuperamos LTV alto com CAC 3x menor que novos usuários, aproveitando intenção latente.",
     rationale:"680k usuários com ticket médio R$54,20, última compra entre 30 e 90 dias atrás. Taxa histórica de reativação em segmentos similares: 23%. Margem incremental estimada: +R$18 por pedido reativado.",
     pills:[{t:"ROAS previsto 5,2x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~680k usuários",c:""},{t:"Meta Retargeting",c:"pu"}],
     pred:{imp:"5,1MM",reach:"1,8MM",clicks:"92K",ctr:"1,80%",cpm:"R$10,80",cpc:"R$0,60",roas:"5,2x"},
     trend:"Usuários inativos de 30–90 dias respondem 2,4x melhor a criativos com ofertas exclusivas de reativação. Carrossel no Instagram tem 38% mais recall nesse segmento vs. estático.",
     price:"Ticket médio projetado: R$54,20 · Faixa P75–P90. Oferta de reativação com 15% de desconto no primeiro pedido recupera hábito sem comprometer margem. Preço âncora sugerido: R$46,90."},
    {sug:false,
     title:"Hipótese 3 — Heavy buyers em janela de pico (sex–dom 19h–22h)",
     thesis:"Se concentrarmos mídia em usuários com padrão de compra em finais de semana no horário noturno de pico, reduzimos CAC aproveitando maior intenção de compra impulsiva.",
     rationale:"3,2MM usuários realizaram 80%+ dos pedidos na janela sex–dom 19h–22h. CPM 18% menor vs. horário padrão. CAC estimado 22% menor. Conversão 2,1x maior em campanhas ativas nessa janela.",
     pills:[{t:"ROAS previsto 5,8x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~3,2MM usuários",c:""},{t:"Meta + TikTok",c:"pu"}],
     pred:{imp:"24,6MM",reach:"8,4MM",clicks:"320K",ctr:"1,30%",cpm:"R$8,90",cpc:"R$0,68",roas:"5,8x"},
     trend:"Conteúdo em vídeo curto (15s) no horário noturno apresentou 3x mais shares na categoria bebidas no último trimestre. TikTok Spark Ads têm 42% mais conversão vs. anúncio padrão nessa janela.",
     price:"Ticket médio projetado: R$42,80 · Faixa P50–P65. Compras nessa janela têm maior suscetibilidade a bundle + frete grátis. Oferta recomendada: bundle de 4 unidades com 10% de desconto."},
    {sug:false,
     title:"Hipótese 4 — Lookalike de convertedores recentes (últimos 15 dias)",
     thesis:"Se ativarmos lookalikes dos convertedores dos últimos 15 dias, expandimos alcance com precisão usando o modelo comportamental 1P de 100MM de usuários do iFood.",
     rationale:"Seed de 45k convertidos recentes gera lookalike estimado de 8,5MM de usuários. Sobreposição comportamental modelada: 68%. Taxa de ativação histórica lookalike 1–3%: 11%. Custo por novo usuário: R$12,40.",
     pills:[{t:"ROAS previsto 3,9x",c:"gr"},{t:"Confiança Média-Alta",c:""},{t:"~8,5MM usuários",c:""},{t:"Meta Lookalike 1–3%",c:"pu"}],
     pred:{imp:"62,0MM",reach:"21,0MM",clicks:"558K",ctr:"0,90%",cpm:"R$11,20",cpc:"R$1,24",roas:"3,9x"},
     trend:"Lookalike 1–3% tem performance 40% superior em períodos sazonais. Criativos de prova social (reviews + UGC) elevam CTR em 28% nesse público.",
     price:"Ticket médio projetado: R$35,60 · Faixa P40–P55. Público de expansão tem menor ticket inicial mas potencial de upgrade com retenção. Preço de entrada sugerido: R$24,90 para first-order."}
  ]

var FEE_TIERS=[
    {max:50000,   feePct:0.100, label:'100% · até R$50k'},
    {max:150000,  feePct:0.085, label:'85% · R$50k–R$150k'},
    {max:350000,  feePct:0.070, label:'70% · R$150k–R$350k'},
    {max:700000,  feePct:0.055, label:'55% · R$350k–R$700k'},
    {max:Infinity,feePct:0.040, label:'40% · acima de R$700k'}
  ]

var AUD_DATA=[
    {name:"Heavy Buyers de Bebidas",
     thesis:"Usuários com 3 ou mais pedidos de bebidas nos últimos 90 dias representam o núcleo de alto valor da categoria — maior LTV e menor custo de conversão por pedido incremental.",
     rationale:"Comportamento recorrente indica fidelidade à categoria. Ticket médio 42% acima da média geral da plataforma. Taxa de resposta a campanhas de retenção: 31%. CAC estimado: R$8,40.",
     estimativa:"~4,2MM usuários",potencial:"Alto ROAS em Meta · Retenção"},
    {name:"Fim de Semana Noturno (sex–dom 19h–01h)",
     thesis:"Usuários com padrão de pedidos concentrado em finais de semana no período noturno têm maior propensão a compras impulsivas de bebidas e ticket por sessão 28% mais alto.",
     rationale:"8,1MM usuários com 70%+ dos pedidos nessa janela. CPM 18% menor vs. horário padrão. Conversão 2,1x maior em campanhas ativas. Janela ideal para Spark Ads e Meta Stories.",
     estimativa:"~8,1MM usuários",potencial:"Volume alto · Remarketing"},
    {name:"Ticket Premium (acima do P75 da categoria)",
     thesis:"Compradores com ticket médio acima do percentil 75 da categoria indicam disposição a pagar por produtos premium, ideal para campanhas de upsell e marcas aspiracionais.",
     rationale:"1,8MM usuários com ticket médio > R$54. CAC maior, porém LTV 3,2x superior à média da base. ROAS histórico de campanhas similares: 5,1x. Recomendado para Meta Feed + Google Search.",
     estimativa:"~1,8MM usuários",potencial:"CAC maior · LTV forte"},
    {name:"Lookalike de Convertedores Recentes",
     thesis:"Expansão de audiência baseada em seed de convertedores dos últimos 30 dias via modelo comportamental 1P do iFood — alta precisão com volume escalável.",
     rationale:"Seed de 45k convertidos gera lookalike de ~12MM usuários. Sobreposição comportamental modelada: 68%. Taxa de ativação histórica de lookalike 1–3%: 11%. Custo de entrada estimado: R$12,40 por novo usuário.",
     estimativa:"~12MM usuários",potencial:"Expansão controlada · Escala"}
  ]

var HYP_CARDS=[
    {sug:true,title:"Hipótese 1 — Compradores Frequentes sem Fidelização à Marca",
     thesis:"Se ativarmos usuários que compraram bebidas 3 ou mais vezes nas últimas 4 semanas, mas nunca escolheram a marca, aumentamos penetração porque já demonstraram alta propensão na categoria.",
     rationale:"2,1MM de usuários do iFood compraram bebidas 3x+ nas últimas 4 semanas sem nenhuma conversão da marca. Ticket médio da categoria: R$38,40. Taxa de conversão esperada: 8,2%.",
     pills:[{t:"ROAS previsto 4,8x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~2,1MM usuários",c:""},{t:"Meta + Google",c:"pu"}]},
    {sug:true,title:"Hipótese 2 — Reativação de Compradores Premium Inativos",
     thesis:"Se reativarmos compradores com ticket médio acima de R$50 inativos há 30–90 dias, recuperamos LTV alto com custo de aquisição 3x menor do que novos usuários.",
     rationale:"680k usuários com ticket médio de R$54,20 em bebidas, última compra entre 30 e 90 dias atrás. Taxa histórica de reativação em segmentos similares: 23%. Margem incremental estimada: +R$18 por pedido reativado.",
     pills:[{t:"ROAS previsto 5,2x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~680k usuários",c:""},{t:"Meta Retargeting",c:"pu"}]},
    {sug:false,title:"Hipótese 3 — Heavy Buyers no Horário de Pico (sex–dom 19h–22h)",
     thesis:"Se concentrarmos mídia em usuários com padrão de compra em finais de semana no horário noturno de pico, reduzimos CAC aproveitando a janela de maior intenção de pedido impulsivo.",
     rationale:"3,2MM de usuários realizaram 80%+ dos seus pedidos de bebidas na janela sex–dom 19h–22h. CPM 18% menor vs. horário padrão. CAC estimado 22% menor. Impressões em horário de pico convertem 2,1x mais.",
     pills:[{t:"ROAS previsto 5,8x",c:"gr"},{t:"Confiança Alta",c:"gr"},{t:"~3,2MM usuários",c:""},{t:"Meta + TikTok",c:"pu"}]},
    {sug:false,title:"Hipótese 4 — Lookalike de Convertedores Recentes (últimos 15 dias)",
     thesis:"Se ativarmos lookalikes dos usuários que converteram nos últimos 15 dias, expandimos alcance com precisão usando o modelo comportamental 1P de 100MM de usuários do iFood.",
     rationale:"Seed de 45k convertidos recentes gera lookalike estimado de 8,5MM de usuários. Sobreposição de comportamento de compra modelada: 68%. Taxa de ativação histórica de lookalike 1–3%: 11%. Custo por novo usuário: R$12,40.",
     pills:[{t:"ROAS previsto 3,9x",c:"gr"},{t:"Confiança Média-Alta",c:""},{t:"~8,5MM usuários",c:""},{t:"Meta Lookalike 1–3%",c:"pu"}]}
  ]

var CROSS_CLIENT_BRANDS=[
    {name:"Coca-Cola",initials:"CC",color:"#E8000B",clients:["iFood Bebidas","Publicis — Bebidas"]},
    {name:"Heineken",initials:"HK",color:"#00843D",clients:["iFood Bebidas","Publicis"]},
    {name:"Pepsi",initials:"PE",color:"#004B93",clients:["Pepsico"]},
    {name:"Gatorade",initials:"GT",color:"#F78F1E",clients:["Pepsico"]},
    {name:"Nivea",initials:"NI",color:"#005A9C",clients:["Publicis"]},
    {name:"Amstel",initials:"AM",color:"#AC1E23",clients:["Publicis"]},
    {name:"Pão de Açúcar",initials:"PA",color:"#E30613",clients:["iFood Mercados"]},
    {name:"Doritos",initials:"DO",color:"#C8102E",clients:["Pepsico"]},
    {name:"Nescafé",initials:"NC",color:"#E42313",clients:["iFood Bebidas","Publicis"]}
  ]